import type { Genre } from '../types'
import atlas from './atlas.json'

// Generated by pipeline/ from MusicBrainz tags and ListenBrainz listening data.

interface RawGenre {
  name: string
  cluster: number
  regions: string[]
  x: number
  y: number
  z: number
  year: number | null
  popularity: number
  artists: number
  similar: number[]
  top: (string | number)[][]
}

export const GENRES: Genre[] = (atlas.genres as RawGenre[]).map((g, id) => ({
  id,
  name: g.name,
  cluster: g.cluster,
  regions: g.regions,
  x: g.x,
  y: g.y,
  z: g.z,
  year: g.year,
  popularity: g.popularity,
  artistCount: g.artists,
  similar: g.similar,
  topArtists: g.top.map(([name, mbid, deezerId]) => ({
    name: String(name),
    mbid: typeof mbid === 'string' ? mbid : undefined,
    deezerId: typeof deezerId === 'number' && deezerId > 0 ? deezerId : typeof mbid === 'number' && mbid > 0 ? mbid : undefined,
  })),
}))

export const CLUSTER_LABELS: string[] = atlas.clusters.map((c) => c.label)

export const REGIONS = ['Global', 'North America', 'Latin America', 'Europe', 'Africa', 'Middle East', 'Asia', 'Oceania'].filter(
  (r) => GENRES.some((g) => g.regions.includes(r)),
)

/** "North America · Europe", or "Global" when no region stands out. */
export function regionLabel(g: Genre) {
  const named = g.regions.filter((r) => r !== 'Global')
  if (!named.length) return 'Global'
  return named.length > 2 ? `${named.slice(0, 2).join(' · ')} +${named.length - 2}` : named.join(' · ')
}

export const DATA_DATE = atlas.fetchedAt
